-- Generated by kUML — schema for "LapisCloud"
-- Dialect: postgres

CREATE TABLE membership_tier (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    contribution_amount DECIMAL(12, 2) NOT NULL,
    billing_interval VARCHAR(9) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (billing_interval IN ('MONTHLY', 'QUARTERLY', 'YEARLY'))
);

CREATE TABLE document_folder (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    parent_folder_id UUID NULL
);

CREATE TABLE gremium (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    type VARCHAR(21) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    quorum_percent INTEGER NOT NULL DEFAULT 50,
    created_at TIMESTAMP NOT NULL,
    CHECK (type IN ('VORSTAND', 'ARBEITSKREIS', 'AUSSCHUSS', 'SONSTIGES', 'MITGLIEDERVERSAMMLUNG'))
);

CREATE TABLE member (
    id UUID NOT NULL PRIMARY KEY,
    display_name VARCHAR(200) NOT NULL,
    email VARCHAR(320) NOT NULL UNIQUE,
    status VARCHAR(11) NOT NULL,
    joined_at DATE NOT NULL,
    anonymized_at TIMESTAMP NULL,
    membership_tier_id UUID NULL,
    CHECK (status IN ('ANTRAG', 'AKTIV', 'GAST', 'AUSGETRETEN'))
);

CREATE TABLE account (
    id UUID NOT NULL PRIMARY KEY,
    password_hash VARCHAR(200) NULL,
    oidc_subject VARCHAR(200) NULL,
    role VARCHAR(9) NOT NULL,
    member_id UUID NOT NULL,
    CHECK (role IN ('MEMBER', 'BOARD', 'TREASURER', 'ADMIN'))
);

CREATE TABLE contribution (
    id UUID NOT NULL PRIMARY KEY,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    amount_due DECIMAL(12, 2) NOT NULL,
    status VARCHAR(7) NOT NULL,
    paid_at TIMESTAMP NULL,
    paid_amount DECIMAL(12, 2) NULL,
    note VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL,
    member_id UUID NOT NULL,
    membership_tier_id UUID NOT NULL,
    CHECK (status IN ('OPEN', 'PAID', 'WAIVED', 'OVERDUE'))
);

CREATE TABLE document (
    id UUID NOT NULL PRIMARY KEY,
    folder_id UUID NOT NULL,
    title VARCHAR(300) NOT NULL,
    current_version_id UUID NULL,
    created_by UUID NOT NULL,
    created_at TIMESTAMP NOT NULL,
    access_level VARCHAR(14) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK (access_level IN ('PUBLIC_MEMBERS', 'BOARD_ONLY', 'ADMIN_ONLY'))
);

CREATE TABLE mailing_list (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NULL,
    created_by UUID NOT NULL
);

CREATE TABLE direct_message (
    id UUID NOT NULL PRIMARY KEY,
    body VARCHAR(10000) NOT NULL,
    sender_id UUID NOT NULL,
    recipient_id UUID NOT NULL,
    sent_at TIMESTAMP NOT NULL,
    read_at TIMESTAMP NULL
);

CREATE TABLE erasure_request (
    id UUID NOT NULL PRIMARY KEY,
    subject_member_id UUID NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    requested_by UUID NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    mode VARCHAR(31) NOT NULL,
    status VARCHAR(9) NOT NULL,
    decided_by UUID NULL,
    decided_at TIMESTAMP NULL,
    decision_note VARCHAR(1000) NULL,
    executed_at TIMESTAMP NULL,
    legal_hold BOOLEAN NOT NULL DEFAULT FALSE,
    outcome_summary VARCHAR(4000) NULL,
    CHECK (mode IN ('ANONYMIZE', 'HARD_DELETE_WHERE_UNCONSTRAINED')),
    CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED'))
);

CREATE TABLE gremium_mitgliedschaft (
    id UUID NOT NULL PRIMARY KEY,
    rolle VARCHAR(15) NOT NULL,
    since DATE NOT NULL,
    until DATE NULL,
    gremium_id UUID NOT NULL,
    member_id UUID NOT NULL,
    CHECK (rolle IN ('VORSITZ', 'STELLV_VORSITZ', 'SCHRIFTFUEHRUNG', 'MITGLIED', 'BEISITZ'))
);

CREATE TABLE ltr_balance (
    member_id UUID NOT NULL PRIMARY KEY,
    balance_ltr DECIMAL(18, 2) NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE document_version (
    id UUID NOT NULL PRIMARY KEY,
    version_number INTEGER NOT NULL,
    file_name VARCHAR(300) NOT NULL,
    mime_type VARCHAR(150) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    storage_key VARCHAR(300) NOT NULL,
    checksum_sha256 VARCHAR(64) NOT NULL,
    uploaded_by UUID NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,
    change_note VARCHAR(1000) NULL,
    document_id UUID NOT NULL
);

CREATE TABLE sitzung (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    location VARCHAR(300) NULL,
    format VARCHAR(8) NOT NULL,
    status VARCHAR(13) NOT NULL,
    called_by UUID NULL,
    called_at TIMESTAMP NULL,
    chair_member_id UUID NULL,
    minute_taker_member_id UUID NULL,
    protocol_document_id UUID NULL,
    created_at TIMESTAMP NOT NULL,
    gremium_id UUID NOT NULL,
    CHECK (format IN ('PRAESENZ', 'ONLINE', 'HYBRID')),
    CHECK (status IN ('GEPLANT', 'DURCHGEFUEHRT', 'ABGESAGT'))
);

CREATE TABLE mailing_list_subscription (
    id UUID NOT NULL PRIMARY KEY,
    subscribed_at TIMESTAMP NOT NULL,
    unsubscribed_at TIMESTAMP NULL,
    mailing_list_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE mailing_message (
    id UUID NOT NULL PRIMARY KEY,
    subject VARCHAR(300) NOT NULL,
    body_text VARCHAR(20000) NOT NULL,
    sent_by UUID NOT NULL,
    sent_at TIMESTAMP NULL,
    status VARCHAR(6) NOT NULL,
    mailing_list_id UUID NOT NULL,
    CHECK (status IN ('DRAFT', 'QUEUED', 'SENT', 'FAILED'))
);

CREATE TABLE dsgvo_audit_log (
    id UUID NOT NULL PRIMARY KEY,
    occurred_at TIMESTAMP NOT NULL,
    actor_member_id UUID NULL,
    actor_role VARCHAR(9) NULL,
    action VARCHAR(17) NOT NULL,
    subject_member_id UUID NOT NULL,
    request_id UUID NULL,
    outcome_summary VARCHAR(4000) NULL,
    legal_basis VARCHAR(500) NULL,
    CHECK (actor_role IN ('MEMBER', 'BOARD', 'TREASURER', 'ADMIN')),
    CHECK (action IN ('EXPORT', 'ERASURE_REQUESTED', 'ERASURE_APPROVED', 'ERASURE_REJECTED', 'ERASURE_EXECUTED'))
);

CREATE TABLE tagesordnungspunkt (
    id UUID NOT NULL PRIMARY KEY,
    position INTEGER NOT NULL,
    title VARCHAR(300) NOT NULL,
    description VARCHAR(4000) NULL,
    presenter_member_id UUID NULL,
    sitzung_id UUID NOT NULL
);

CREATE TABLE anwesenheit (
    id UUID NOT NULL PRIMARY KEY,
    status VARCHAR(14) NOT NULL,
    represented_by_member_id UUID NULL,
    note VARCHAR(500) NULL,
    recorded_at TIMESTAMP NOT NULL,
    sitzung_id UUID NOT NULL,
    member_id UUID NOT NULL,
    CHECK (status IN ('ANWESEND', 'ENTSCHULDIGT', 'UNENTSCHULDIGT', 'VERTRETEN'))
);

CREATE TABLE mailing_delivery_log (
    id UUID NOT NULL PRIMARY KEY,
    delivered_at TIMESTAMP NOT NULL,
    delivery_status VARCHAR(20) NOT NULL,
    mailing_message_id UUID NOT NULL,
    member_id UUID NOT NULL,
    CHECK (delivery_status IN ('SENT', 'BOUNCED', 'SKIPPED_UNSUBSCRIBED'))
);

CREATE TABLE beschluss (
    id UUID NOT NULL PRIMARY KEY,
    number VARCHAR(50) NOT NULL,
    title VARCHAR(300) NOT NULL,
    text VARCHAR(4000) NOT NULL,
    votes_yes INTEGER NOT NULL,
    votes_no INTEGER NOT NULL,
    votes_abstain INTEGER NOT NULL,
    quorum_met BOOLEAN NOT NULL,
    status VARCHAR(10) NOT NULL,
    decided_at TIMESTAMP NOT NULL,
    recorded_by UUID NOT NULL,
    resolution_mode VARCHAR(14) NOT NULL DEFAULT 'GREMIUM_QUORUM',
    abstimmung_id UUID NULL,
    wahl_id UUID NULL,
    sitzung_id UUID NOT NULL,
    tagesordnungspunkt_id UUID NULL,
    CHECK (status IN ('ANGENOMMEN', 'ABGELEHNT', 'VERTAGT')),
    CHECK (resolution_mode IN ('GREMIUM_QUORUM', 'MERITOKRATISCH', 'DEMOKRATISCH'))
);

CREATE TABLE antrag (
    id UUID NOT NULL PRIMARY KEY,
    target_gremium_id UUID NOT NULL,
    title VARCHAR(300) NOT NULL,
    begruendung VARCHAR(4000) NOT NULL,
    text VARCHAR(4000) NOT NULL,
    submitter_member_id UUID NOT NULL,
    status VARCHAR(21) NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    reviewed_by UUID NULL,
    reviewed_at TIMESTAMP NULL,
    review_note VARCHAR(1000) NULL,
    withdrawn_at TIMESTAMP NULL,
    sitzung_id UUID NULL,
    tagesordnungspunkt_id UUID NULL,
    beschluss_id UUID NULL,
    CHECK (status IN ('EINGEREICHT', 'GEPRUEFT', 'ABGELEHNT_VORPRUEFUNG', 'TERMINIERT', 'BESCHLOSSEN', 'ABGELEHNT', 'VERTAGT', 'ZURUECKGEZOGEN'))
);

CREATE TABLE abstimmung (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    status VARCHAR(11) NOT NULL,
    opened_by UUID NOT NULL,
    opened_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP NULL,
    winner_option_id UUID NULL,
    second_price_ltr DECIMAL(18, 2) NULL,
    antrag_id UUID NOT NULL,
    sitzung_id UUID NOT NULL,
    beschluss_id UUID NULL,
    CHECK (status IN ('OFFEN', 'GESCHLOSSEN', 'ABGEBROCHEN'))
);

CREATE TABLE wahl (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    wahl_typ VARCHAR(14) NOT NULL,
    geheim BOOLEAN NOT NULL,
    sitze_count INTEGER NOT NULL,
    ziel_gremium_id UUID NULL,
    ziel_rolle VARCHAR(15) NULL,
    required_majority_percent INTEGER NOT NULL,
    status VARCHAR(27) NOT NULL,
    opened_by UUID NOT NULL,
    opened_at TIMESTAMP NOT NULL,
    candidate_list_approved_at TIMESTAMP NULL,
    voting_opened_at TIMESTAMP NULL,
    voting_closed_at TIMESTAMP NULL,
    tally_threshold INTEGER NOT NULL,
    tally_run_at TIMESTAMP NULL,
    antrag_id UUID NOT NULL,
    sitzung_id UUID NOT NULL,
    beschluss_id UUID NULL,
    CHECK (wahl_typ IN ('JA_NEIN', 'EINZELWAHL', 'MEHRFACHWAHL', 'LISTENWAHL', 'RANGLISTENWAHL')),
    CHECK (ziel_rolle IN ('VORSITZ', 'STELLV_VORSITZ', 'SCHRIFTFUEHRUNG', 'MITGLIED', 'BEISITZ')),
    CHECK (status IN ('VORBEREITUNG', 'KANDIDATENLISTE_FREIGEGEBEN', 'OFFEN', 'GESCHLOSSEN', 'AUSGEZAEHLT', 'ABGEBROCHEN'))
);

CREATE TABLE abstimmung_option (
    id UUID NOT NULL PRIMARY KEY,
    label VARCHAR(200) NOT NULL,
    position INTEGER NOT NULL,
    abstimmung_id UUID NOT NULL
);

CREATE TABLE wahl_kandidatur (
    id UUID NOT NULL PRIMARY KEY,
    motivation_text VARCHAR(1000) NULL,
    submitted_at TIMESTAMP NOT NULL,
    withdrawn_at TIMESTAMP NULL,
    wahl_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE wahl_wahlvorstand (
    id UUID NOT NULL PRIMARY KEY,
    appointed_at TIMESTAMP NOT NULL,
    wahl_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE wahl_wahlberechtigt (
    id UUID NOT NULL PRIMARY KEY,
    wahl_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE wahl_teilnahme (
    id UUID NOT NULL PRIMARY KEY,
    voted_at TIMESTAMP NOT NULL,
    wahl_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE wahl_freigabe (
    id UUID NOT NULL PRIMARY KEY,
    approved_at TIMESTAMP NOT NULL,
    wahl_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE wahl_stimmzettel (
    id UUID NOT NULL PRIMARY KEY,
    receipt_code VARCHAR(40) NOT NULL,
    cast_at TIMESTAMP NOT NULL,
    wahl_id UUID NOT NULL,
    member_id UUID NULL
);

CREATE TABLE abstimmung_stimme (
    id UUID NOT NULL PRIMARY KEY,
    option_id UUID NOT NULL,
    stake_ltr DECIMAL(18, 2) NOT NULL,
    settled_ltr DECIMAL(18, 2) NULL,
    cast_at TIMESTAMP NOT NULL,
    abstimmung_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE wahl_option (
    id UUID NOT NULL PRIMARY KEY,
    label VARCHAR(200) NOT NULL,
    position INTEGER NOT NULL,
    kandidatur_id UUID NULL,
    wahl_id UUID NOT NULL
);

CREATE TABLE wahl_stimmzettel_auswahl (
    id UUID NOT NULL PRIMARY KEY,
    stimmzettel_id UUID NOT NULL,
    option_id UUID NOT NULL
);

-- Foreign Keys

ALTER TABLE member ADD CONSTRAINT fk_member_membership_tier_id FOREIGN KEY (membership_tier_id) REFERENCES membership_tier(id);
ALTER TABLE account ADD CONSTRAINT fk_account_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE contribution ADD CONSTRAINT fk_contribution_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE contribution ADD CONSTRAINT fk_contribution_membership_tier_id FOREIGN KEY (membership_tier_id) REFERENCES membership_tier(id);
ALTER TABLE document ADD CONSTRAINT fk_document_folder_id FOREIGN KEY (folder_id) REFERENCES document_folder(id);
ALTER TABLE document ADD CONSTRAINT fk_document_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE document_version ADD CONSTRAINT fk_document_version_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES member(id);
ALTER TABLE document_version ADD CONSTRAINT fk_document_version_document_id FOREIGN KEY (document_id) REFERENCES document(id);
ALTER TABLE mailing_list ADD CONSTRAINT fk_mailing_list_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE mailing_list_subscription ADD CONSTRAINT fk_mailing_list_subscription_mailing_list_id FOREIGN KEY (mailing_list_id) REFERENCES mailing_list(id);
ALTER TABLE mailing_list_subscription ADD CONSTRAINT fk_mailing_list_subscription_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE mailing_message ADD CONSTRAINT fk_mailing_message_sent_by FOREIGN KEY (sent_by) REFERENCES member(id);
ALTER TABLE mailing_message ADD CONSTRAINT fk_mailing_message_mailing_list_id FOREIGN KEY (mailing_list_id) REFERENCES mailing_list(id);
ALTER TABLE mailing_delivery_log ADD CONSTRAINT fk_mailing_delivery_log_mailing_message_id FOREIGN KEY (mailing_message_id) REFERENCES mailing_message(id);
ALTER TABLE mailing_delivery_log ADD CONSTRAINT fk_mailing_delivery_log_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE direct_message ADD CONSTRAINT fk_direct_message_sender_id FOREIGN KEY (sender_id) REFERENCES member(id);
ALTER TABLE direct_message ADD CONSTRAINT fk_direct_message_recipient_id FOREIGN KEY (recipient_id) REFERENCES member(id);
ALTER TABLE erasure_request ADD CONSTRAINT fk_erasure_request_subject_member_id FOREIGN KEY (subject_member_id) REFERENCES member(id);
ALTER TABLE erasure_request ADD CONSTRAINT fk_erasure_request_requested_by FOREIGN KEY (requested_by) REFERENCES member(id);
ALTER TABLE erasure_request ADD CONSTRAINT fk_erasure_request_decided_by FOREIGN KEY (decided_by) REFERENCES member(id);
ALTER TABLE dsgvo_audit_log ADD CONSTRAINT fk_dsgvo_audit_log_actor_member_id FOREIGN KEY (actor_member_id) REFERENCES member(id);
ALTER TABLE dsgvo_audit_log ADD CONSTRAINT fk_dsgvo_audit_log_subject_member_id FOREIGN KEY (subject_member_id) REFERENCES member(id);
ALTER TABLE dsgvo_audit_log ADD CONSTRAINT fk_dsgvo_audit_log_request_id FOREIGN KEY (request_id) REFERENCES erasure_request(id);
ALTER TABLE gremium_mitgliedschaft ADD CONSTRAINT fk_gremium_mitgliedschaft_gremium_id FOREIGN KEY (gremium_id) REFERENCES gremium(id);
ALTER TABLE gremium_mitgliedschaft ADD CONSTRAINT fk_gremium_mitgliedschaft_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE sitzung ADD CONSTRAINT fk_sitzung_called_by FOREIGN KEY (called_by) REFERENCES member(id);
ALTER TABLE sitzung ADD CONSTRAINT fk_sitzung_chair_member_id FOREIGN KEY (chair_member_id) REFERENCES member(id);
ALTER TABLE sitzung ADD CONSTRAINT fk_sitzung_minute_taker_member_id FOREIGN KEY (minute_taker_member_id) REFERENCES member(id);
ALTER TABLE sitzung ADD CONSTRAINT fk_sitzung_protocol_document_id FOREIGN KEY (protocol_document_id) REFERENCES document(id);
ALTER TABLE sitzung ADD CONSTRAINT fk_sitzung_gremium_id FOREIGN KEY (gremium_id) REFERENCES gremium(id);
ALTER TABLE tagesordnungspunkt ADD CONSTRAINT fk_tagesordnungspunkt_presenter_member_id FOREIGN KEY (presenter_member_id) REFERENCES member(id);
ALTER TABLE tagesordnungspunkt ADD CONSTRAINT fk_tagesordnungspunkt_sitzung_id FOREIGN KEY (sitzung_id) REFERENCES sitzung(id);
ALTER TABLE anwesenheit ADD CONSTRAINT fk_anwesenheit_represented_by_member_id FOREIGN KEY (represented_by_member_id) REFERENCES member(id);
ALTER TABLE anwesenheit ADD CONSTRAINT fk_anwesenheit_sitzung_id FOREIGN KEY (sitzung_id) REFERENCES sitzung(id);
ALTER TABLE anwesenheit ADD CONSTRAINT fk_anwesenheit_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE beschluss ADD CONSTRAINT fk_beschluss_recorded_by FOREIGN KEY (recorded_by) REFERENCES member(id);
ALTER TABLE beschluss ADD CONSTRAINT fk_beschluss_sitzung_id FOREIGN KEY (sitzung_id) REFERENCES sitzung(id);
ALTER TABLE beschluss ADD CONSTRAINT fk_beschluss_tagesordnungspunkt_id FOREIGN KEY (tagesordnungspunkt_id) REFERENCES tagesordnungspunkt(id);
ALTER TABLE antrag ADD CONSTRAINT fk_antrag_target_gremium_id FOREIGN KEY (target_gremium_id) REFERENCES gremium(id);
ALTER TABLE antrag ADD CONSTRAINT fk_antrag_submitter_member_id FOREIGN KEY (submitter_member_id) REFERENCES member(id);
ALTER TABLE antrag ADD CONSTRAINT fk_antrag_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES member(id);
ALTER TABLE antrag ADD CONSTRAINT fk_antrag_sitzung_id FOREIGN KEY (sitzung_id) REFERENCES sitzung(id);
ALTER TABLE antrag ADD CONSTRAINT fk_antrag_tagesordnungspunkt_id FOREIGN KEY (tagesordnungspunkt_id) REFERENCES tagesordnungspunkt(id);
ALTER TABLE antrag ADD CONSTRAINT fk_antrag_beschluss_id FOREIGN KEY (beschluss_id) REFERENCES beschluss(id);
ALTER TABLE abstimmung ADD CONSTRAINT fk_abstimmung_opened_by FOREIGN KEY (opened_by) REFERENCES member(id);
ALTER TABLE abstimmung ADD CONSTRAINT fk_abstimmung_antrag_id FOREIGN KEY (antrag_id) REFERENCES antrag(id);
ALTER TABLE abstimmung ADD CONSTRAINT fk_abstimmung_sitzung_id FOREIGN KEY (sitzung_id) REFERENCES sitzung(id);
ALTER TABLE abstimmung ADD CONSTRAINT fk_abstimmung_beschluss_id FOREIGN KEY (beschluss_id) REFERENCES beschluss(id);
ALTER TABLE abstimmung_option ADD CONSTRAINT fk_abstimmung_option_abstimmung_id FOREIGN KEY (abstimmung_id) REFERENCES abstimmung(id);
ALTER TABLE abstimmung_stimme ADD CONSTRAINT fk_abstimmung_stimme_option_id FOREIGN KEY (option_id) REFERENCES abstimmung_option(id);
ALTER TABLE abstimmung_stimme ADD CONSTRAINT fk_abstimmung_stimme_abstimmung_id FOREIGN KEY (abstimmung_id) REFERENCES abstimmung(id);
ALTER TABLE abstimmung_stimme ADD CONSTRAINT fk_abstimmung_stimme_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE wahl ADD CONSTRAINT fk_wahl_ziel_gremium_id FOREIGN KEY (ziel_gremium_id) REFERENCES gremium(id);
ALTER TABLE wahl ADD CONSTRAINT fk_wahl_opened_by FOREIGN KEY (opened_by) REFERENCES member(id);
ALTER TABLE wahl ADD CONSTRAINT fk_wahl_antrag_id FOREIGN KEY (antrag_id) REFERENCES antrag(id);
ALTER TABLE wahl ADD CONSTRAINT fk_wahl_sitzung_id FOREIGN KEY (sitzung_id) REFERENCES sitzung(id);
ALTER TABLE wahl ADD CONSTRAINT fk_wahl_beschluss_id FOREIGN KEY (beschluss_id) REFERENCES beschluss(id);
ALTER TABLE wahl_kandidatur ADD CONSTRAINT fk_wahl_kandidatur_wahl_id FOREIGN KEY (wahl_id) REFERENCES wahl(id);
ALTER TABLE wahl_kandidatur ADD CONSTRAINT fk_wahl_kandidatur_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE wahl_option ADD CONSTRAINT fk_wahl_option_kandidatur_id FOREIGN KEY (kandidatur_id) REFERENCES wahl_kandidatur(id);
ALTER TABLE wahl_option ADD CONSTRAINT fk_wahl_option_wahl_id FOREIGN KEY (wahl_id) REFERENCES wahl(id);
ALTER TABLE wahl_wahlvorstand ADD CONSTRAINT fk_wahl_wahlvorstand_wahl_id FOREIGN KEY (wahl_id) REFERENCES wahl(id);
ALTER TABLE wahl_wahlvorstand ADD CONSTRAINT fk_wahl_wahlvorstand_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE wahl_wahlberechtigt ADD CONSTRAINT fk_wahl_wahlberechtigt_wahl_id FOREIGN KEY (wahl_id) REFERENCES wahl(id);
ALTER TABLE wahl_wahlberechtigt ADD CONSTRAINT fk_wahl_wahlberechtigt_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE wahl_teilnahme ADD CONSTRAINT fk_wahl_teilnahme_wahl_id FOREIGN KEY (wahl_id) REFERENCES wahl(id);
ALTER TABLE wahl_teilnahme ADD CONSTRAINT fk_wahl_teilnahme_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE wahl_freigabe ADD CONSTRAINT fk_wahl_freigabe_wahl_id FOREIGN KEY (wahl_id) REFERENCES wahl(id);
ALTER TABLE wahl_freigabe ADD CONSTRAINT fk_wahl_freigabe_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE wahl_stimmzettel ADD CONSTRAINT fk_wahl_stimmzettel_wahl_id FOREIGN KEY (wahl_id) REFERENCES wahl(id);
ALTER TABLE wahl_stimmzettel ADD CONSTRAINT fk_wahl_stimmzettel_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE wahl_stimmzettel_auswahl ADD CONSTRAINT fk_wahl_stimmzettel_auswahl_stimmzettel_id FOREIGN KEY (stimmzettel_id) REFERENCES wahl_stimmzettel(id);
ALTER TABLE wahl_stimmzettel_auswahl ADD CONSTRAINT fk_wahl_stimmzettel_auswahl_option_id FOREIGN KEY (option_id) REFERENCES wahl_option(id);
ALTER TABLE ltr_balance ADD CONSTRAINT fk_ltr_balance_member_id FOREIGN KEY (member_id) REFERENCES member(id);

-- Indexes

CREATE UNIQUE INDEX uq_account_member_id ON account (member_id);
CREATE UNIQUE INDEX uq_contribution_member_tier_period ON contribution (member_id, membership_tier_id, period_start, period_end);
CREATE INDEX idx_contribution_member ON contribution (member_id);
CREATE INDEX idx_contribution_status ON contribution (status);
CREATE INDEX idx_document_folder ON document (folder_id);
CREATE UNIQUE INDEX uq_document_version_number ON document_version (document_id, version_number);
CREATE INDEX idx_document_version_document ON document_version (document_id);
CREATE UNIQUE INDEX uq_mailing_subscription_list_member ON mailing_list_subscription (mailing_list_id, member_id);
CREATE INDEX idx_mailing_subscription_list ON mailing_list_subscription (mailing_list_id);
CREATE INDEX idx_mailing_message_list ON mailing_message (mailing_list_id);
CREATE INDEX idx_direct_message_recipient ON direct_message (recipient_id);
CREATE INDEX idx_direct_message_sender ON direct_message (sender_id);
CREATE INDEX idx_erasure_request_subject ON erasure_request (subject_member_id);
CREATE INDEX idx_erasure_request_status ON erasure_request (status);
CREATE INDEX idx_dsgvo_audit_log_subject ON dsgvo_audit_log (subject_member_id);
CREATE INDEX idx_dsgvo_audit_log_request ON dsgvo_audit_log (request_id);
CREATE INDEX idx_gremium_mitgliedschaft_gremium ON gremium_mitgliedschaft (gremium_id);
CREATE INDEX idx_gremium_mitgliedschaft_member ON gremium_mitgliedschaft (member_id);
CREATE INDEX idx_sitzung_gremium ON sitzung (gremium_id);
CREATE UNIQUE INDEX uq_tagesordnungspunkt_position ON tagesordnungspunkt (sitzung_id, position);
CREATE INDEX idx_tagesordnungspunkt_sitzung ON tagesordnungspunkt (sitzung_id);
CREATE UNIQUE INDEX uq_anwesenheit_member ON anwesenheit (sitzung_id, member_id);
CREATE INDEX idx_anwesenheit_sitzung ON anwesenheit (sitzung_id);
CREATE INDEX idx_beschluss_sitzung ON beschluss (sitzung_id);
CREATE INDEX idx_antrag_target_gremium ON antrag (target_gremium_id);
CREATE INDEX idx_antrag_status ON antrag (status);
CREATE INDEX idx_antrag_submitter ON antrag (submitter_member_id);
CREATE INDEX idx_antrag_sitzung ON antrag (sitzung_id);
CREATE INDEX idx_abstimmung_antrag ON abstimmung (antrag_id);
CREATE INDEX idx_abstimmung_status ON abstimmung (status);
CREATE INDEX idx_abstimmung_option_abstimmung ON abstimmung_option (abstimmung_id);
CREATE UNIQUE INDEX uq_abstimmung_stimme_member ON abstimmung_stimme (abstimmung_id, member_id);
CREATE INDEX idx_abstimmung_stimme_abstimmung ON abstimmung_stimme (abstimmung_id);
CREATE INDEX idx_abstimmung_stimme_member ON abstimmung_stimme (member_id);
CREATE INDEX idx_wahl_antrag ON wahl (antrag_id);
CREATE INDEX idx_wahl_sitzung ON wahl (sitzung_id);
CREATE INDEX idx_wahl_status ON wahl (status);
CREATE INDEX idx_wahl_kandidatur_wahl ON wahl_kandidatur (wahl_id);
CREATE INDEX idx_wahl_kandidatur_member ON wahl_kandidatur (member_id);
CREATE INDEX idx_wahl_option_wahl ON wahl_option (wahl_id);
CREATE UNIQUE INDEX uq_wahl_wahlvorstand_member ON wahl_wahlvorstand (wahl_id, member_id);
CREATE INDEX idx_wahl_wahlvorstand_wahl ON wahl_wahlvorstand (wahl_id);
CREATE UNIQUE INDEX uq_wahl_wahlberechtigt_member ON wahl_wahlberechtigt (wahl_id, member_id);
CREATE INDEX idx_wahl_wahlberechtigt_wahl ON wahl_wahlberechtigt (wahl_id);
CREATE UNIQUE INDEX uq_wahl_teilnahme_member ON wahl_teilnahme (wahl_id, member_id);
CREATE INDEX idx_wahl_teilnahme_wahl ON wahl_teilnahme (wahl_id);
CREATE UNIQUE INDEX uq_wahl_freigabe_member ON wahl_freigabe (wahl_id, member_id);
CREATE INDEX idx_wahl_freigabe_wahl ON wahl_freigabe (wahl_id);
CREATE UNIQUE INDEX uq_wahl_stimmzettel_member ON wahl_stimmzettel (wahl_id, member_id);
CREATE INDEX idx_wahl_stimmzettel_wahl ON wahl_stimmzettel (wahl_id);
CREATE INDEX idx_wahl_stimmzettel_auswahl_stimmzettel ON wahl_stimmzettel_auswahl (stimmzettel_id);
CREATE INDEX idx_wahl_stimmzettel_auswahl_option ON wahl_stimmzettel_auswahl (option_id);

