plugins {
    alias(libs.plugins.kotlin.jvm)
    application
}

kotlin {
    // Kept in lockstep with lapis-shared — see the comment there. Needed
    // to load Kilua RPC's JVM-25-compiled classes at runtime.
    jvmToolchain(26)
}

application {
    mainClass.set("network.lapis.cloud.server.ApplicationKt")
}

// ADR-0016 MDA codegen verification pipeline — real-codegen part (a): "does the generated Kotlin
// actually compile?". Deliberately a separate, isolated Gradle source set (not `main`/`test`) so
// this never touches the production compile classpath:
//   - `CodegenParitySeedTest` (in `src/test/kotlin`) runs `UmlToExposedViaErmScriptTransformer`
//     for every domain script and writes the generated `Table`/enum sources into
//     `build/generated/kuml/<package-path>/*.kt` as a *side effect* of running `test`.
//   - This `kumlGenerated` source set then compiles exactly those written files against a small,
//     Exposed-only classpath. A syntactically/semantically invalid generated file fails the build
//     right here instead of silently rotting.
// No custom `doFirst`/`doLast` Gradle task is used to do the file-writing (see CLAUDE.md's
// kUML-Repo-Konventionen "Custom-Task-Config-Cache-Falle" — Gradle 9's configuration cache has
// repeatedly broken on custom tasks that touch external file directories in this codebase); the
// file-writing lives in ordinary test code instead, exactly like
// `VaultExamplesRenderTest.kt`'s `afterSpec` pattern in the kUML repo.
sourceSets {
    val kumlGenerated by creating {
        kotlin.srcDir(layout.buildDirectory.dir("generated/kuml"))
    }
}

val kumlGeneratedImplementation by configurations.getting

dependencies {
    implementation(project(":lapis-shared"))

    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.netty)
    implementation(libs.ktor.server.call.logging)
    implementation(libs.ktor.server.content.negotiation)
    implementation(libs.ktor.serialization.kotlinx.json)
    implementation(libs.ktor.server.compression)
    implementation(libs.ktor.server.partial.content)
    implementation(libs.ktor.server.auto.head.response)
    implementation(libs.ktor.server.status.pages)
    implementation(libs.logback.classic)

    implementation(libs.exposed.core)
    implementation(libs.exposed.jdbc)
    implementation(libs.exposed.dao)
    implementation(libs.exposed.java.time)
    implementation(libs.exposed.kotlin.datetime)
    implementation(libs.flyway.core)
    implementation(libs.flyway.database.postgresql)
    implementation(libs.postgresql)
    implementation(libs.hikaricp)

    testImplementation(libs.ktor.server.test.host)
    testImplementation(libs.kotest.runner.junit5)
    testImplementation(libs.kotest.assertions.core)
    testImplementation(libs.kotest.property)
    testImplementation(libs.h2)

    // kUML MDA persistence pipeline (ADR-0016) — see gradle/libs.versions.toml for why these
    // are test-scoped only. Drives SchemaDriftTest: evaluates src/main/kuml/*.kuml.kts via
    // KumlScriptHost, runs UmlToErmTransformer -> ErmToExposedTransformer / ErmSqlDdlGenerator,
    // and diffs the result against the real H2-migrated schema and the hand-written Table
    // objects (verification-only — the hand-written Table objects remain the compiled/runtime
    // artifact; see docs/architecture/domain-model.adoc "MDA-Pipeline / ADR-0016").
    testImplementation(libs.kuml.core.model)
    testImplementation(libs.kuml.core.dsl)
    testImplementation(libs.kuml.core.script)
    testImplementation(libs.kuml.metamodel.uml)
    testImplementation(libs.kuml.metamodel.erm)
    testImplementation(libs.kuml.profile.api)
    testImplementation(libs.kuml.profile.erm)
    testImplementation(libs.kuml.codegen.api)
    testImplementation(libs.kuml.codegen.m2m)
    testImplementation(libs.kuml.transform.uml.to.erm)
    testImplementation(libs.kuml.codegen.m2m.exposed)
    testImplementation(libs.kuml.gen.sql)
    testImplementation(libs.kotlin.scripting.jvm.host)
    testImplementation(libs.kotlin.scripting.common)
    testImplementation(libs.kotlin.scripting.jvm)

    // Verification-only compile classpath for CodegenParitySeedTest's generated output (see the
    // `kumlGenerated` source set above). Bewusst isoliert von `implementation`/`testImplementation`
    // — berührt den Produktivpfad nicht. `exposed-java-time` is needed because ErmExposedEmitter
    // renders `date()`/`datetime()` columns exclusively via `org.jetbrains.exposed.v1.javatime.*`.
    kumlGeneratedImplementation(libs.exposed.core)
    kumlGeneratedImplementation(libs.exposed.java.time)
}

// The Kotlin JVM Gradle plugin auto-registers `compileKumlGeneratedKotlin` for the `kumlGenerated`
// source set above. It must run after `test` (which writes the sources it compiles) and gates
// `check` — a syntactically/semantically invalid generated file fails `./gradlew clean check`.
//
// Declaring the directory as a `test` task *output* (not just a plain `dependsOn`) matters here:
// without it, a `./gradlew clean check` run (this repo's mandatory pre-build step, see CLAUDE.md)
// has been observed to make `compileKumlGeneratedKotlin` report NO-SOURCE and silently skip
// compilation entirely — Gradle's incremental/file-system-watching layer does not reliably pick
// up files written as an undeclared side effect of `test` immediately after the directory was
// freshly re-created by `clean`. Declaring the output wires it into Gradle's normal
// producer/consumer up-to-date tracking, which fixes this reliably.
tasks.test {
    useJUnitPlatform()
    outputs.dir(layout.buildDirectory.dir("generated/kuml"))
}

tasks.named("compileKumlGeneratedKotlin") {
    dependsOn(tasks.test)
}

// ktlint auto-registers a check task per source set, including the new `kumlGenerated` one. Since
// its input directory is now a declared `test` output (see above), Gradle's task-validation
// requires an explicit ordering dependency here too, or `./gradlew clean check` fails with an
// "implicit dependency" configuration error.
tasks.named("runKtlintCheckOverKumlGeneratedSourceSet") {
    dependsOn(tasks.test)
}

tasks.check {
    dependsOn("compileKumlGeneratedKotlin")
}
